// Every project, newest first. cats: institute | ml | hack | build
window.CV_PROJECTS = [
  { y: '2026', name: 'IIT Mandi LaTeX', ctx: 'Lead · UG Academic Council', cats: 'institute build',
    desc: 'Institute-hosted Overleaf alternative for ~3,500 users: first-come compile queue, a 50-user cap with a waiting room, 500 MB quotas, nightly off-host backups and an IIT Mandi template pack. Costed at ₹1.26 lakh one-time against ₹11.29 lakh a year for Overleaf.',
    stack: 'Overleaf CE · Node.js · Docker · CI' },
  { y: '2026', name: 'Academic Section website update', ctx: 'Solo · Academic Affairs', cats: 'institute',
    desc: '34 proposed changes to academics.iitmandi.ac.in: 568 Board- and Senate-approved courses added, 28 course titles corrected, 23 repeated rows removed, the 2026 Ordinance and Handbook linked.',
    stack: 'HTML · Git', link: 'https://github.com/TayalAditya/academics-iitmandi-website' },
  { y: '2026', name: 'TinkerBench', ctx: 'Solo · Atal Tinkering Lab', cats: 'institute build',
    desc: 'A browser electronics bench. Solves the circuit by nodal analysis every frame (diodes, transistors, relays, a working 555 timer) and runs Arduino C++ translated to JavaScript, with Servo, LCD, DHT and RFID stubs. ~72 parts, 11 missions.',
    stack: 'JavaScript · Canvas · nginx' },
  { y: '2026', name: 'Simulation Lab & NCERT Sim', ctx: 'Solo · Atal Tinkering Lab', cats: 'institute build',
    desc: '23 Class 9–12 physics and chemistry experiments and 26 NCERT Class 11–12 physics practicals, each a live lab record with graphs and an everyday scene.',
    stack: 'JavaScript · Docker' },
  { y: '2026', name: 'Faculty Leave Portal', ctx: 'Solo · Dean of Faculty Affairs', cats: 'institute build',
    desc: 'Phase 1 of faculty leave management from the institute PRD. Balances derived from an append-only ledger, triggers that refuse edits, two-phase hold and debit, real service rules. 324 requirements traced, 321 tests.',
    stack: 'Fastify · Prisma · React · SQLite · Raspberry Pi' },
  { y: '2026', name: 'TestPlatform', ctx: 'Solo · online examinations', cats: 'institute build',
    desc: 'Student, teacher and admin portals with organisations. Server-authoritative timers in Redis, Socket.IO live rooms, shuffled papers, auto-grading for MCQ, multi-select and numeric answers, OTP over email and WhatsApp. Hardened after a self-audit.',
    stack: 'Next.js · Express · Socket.IO · PostgreSQL · Redis' },
  { y: '2026', name: 'Campus Pi hosting', ctx: 'Solo · infrastructure', cats: 'build',
    desc: 'One Raspberry Pi 5 on the campus network serves six services. GitHub Pages redirectors follow its changing address and publish health checks every 15 minutes.',
    stack: 'Raspberry Pi · nginx · systemd · GitHub Pages', link: 'https://github.com/TayalAditya/TayalAditya.github.io' },
  { y: '2026', name: 'RASA Materials Lab website', ctx: 'Solo · research group site', cats: 'institute build',
    desc: 'Astro site for an IIT Mandi research group. Its admin panel rebuilds the site and commits back to GitHub, with history and undo.',
    stack: 'Astro · Tailwind' },
  { y: '2026', name: 'FinFabric', ctx: 'Team lead · IDBI Innovate 2026', cats: 'hack build',
    desc: 'Five live banking prototypes: an MSME health card, a mutual-fund companion with live NAVs and SIP maths, lead scoring, a default early-warning model and a reconciliation copilot with fuzzy matching.',
    stack: 'JavaScript · Vercel', link: 'https://github.com/TayalAditya/finfabric-idbi-suite' },
  { y: '2026', name: 'GBNet improvements', ctx: 'Research · camouflaged objects', cats: 'ml',
    desc: '71 documented experiment phases. Beat the reproduced baseline on 42 of 42 dataset-metric checks (6 datasets × 7 metrics) with dataset-routed test-time augmentation and blends.',
    stack: 'PyTorch' },
  { y: '2026', name: 'PurrPedia', ctx: 'Solo · HackTheKitty 2026', cats: 'hack build',
    desc: 'Cat encyclopedia with 247 breeds, a personality quiz and scheduled postcards on Temporal Cloud workflows. Fixed all 5 findings from an Aikido security audit.',
    stack: 'Next.js 16 · Prisma · Temporal · Fabric.js', link: 'https://github.com/TayalAditya/purrpedia' },
  { y: '2026', name: 'FlowAI', ctx: 'Solo · Vibe2Ship 2026', cats: 'hack build',
    desc: 'Gemini multi-agent productivity app: brain dump, goal decomposer, scheduler and reminders.',
    stack: 'Next.js · Gemini · Firebase', link: 'https://github.com/TayalAditya/FlowAI' },
  { y: '2026', name: 'SevaVoice', ctx: 'Solo · HACKHAZARDS ’26', cats: 'hack build',
    desc: 'Turns confusing public-service notices into verified action plans in 14 Indian languages, with voice in 11. Budget and rate guards, 63 Playwright checks.',
    stack: 'React · TypeScript · Express · Sarvam AI', link: 'https://sevavoice.vercel.app' },
  { y: '2026', name: 'Vidyut AI', ctx: 'Solo · ET AI Hackathon 2.0', cats: 'hack ml',
    desc: 'Citation-grounded questions and answers over industrial safety documents (OSHA, CSB, OISD, NASA, Factories Act), with Hindi support.',
    stack: 'Groq · FastAPI · Streamlit', link: 'https://github.com/TayalAditya/vidyut-ai' },
  { y: '2026', name: 'CyberShield', ctx: 'Team of 2 · PSBs Hackathon, IIT Hyderabad', cats: 'hack ml',
    desc: 'Mule-account detection on 9,082 accounts with a 0.89% base rate and 3,925 columns. Removed 793 dead columns and caught a leaking feature. Plus a risk-weighted fraudulent-APK scorer.',
    stack: 'Python · pandas · scikit-learn' },
  { y: '2026', name: 'Sahayak', ctx: 'Solo · KSP Datathon 2026', cats: 'hack ml',
    desc: 'English and Kannada questions to SQL over 3,500 FIRs. Read-only SQL guard, every answer shows its SQL and rows, IPC to BNS crosswalk.',
    stack: 'Qwen 2.5 Coder · Zoho Catalyst · FastAPI · React', link: 'https://github.com/TayalAditya/sahayak-ksp' },
  { y: '2026', name: 'DeepMatch', ctx: 'Solo · India Runs, Redrob × Hack2Skill', cats: 'hack ml',
    desc: 'Three-stage candidate ranker: rules narrow 100K to 5K, MiniLM scores them, signals fuse. Six heuristics catch fake profiles. ~75 s on a CPU.',
    stack: 'Python · sentence-transformers', link: 'https://github.com/TayalAditya/DeepMatch' },
  { y: '2026', name: 'PSCDL 2026', ctx: 'Solo · Vehant Research Labs', cats: 'ml hack',
    desc: 'Persistent scene change detection with classical CV: CIE-Lab differencing, two persistence clocks and an adaptive median + 6·MAD threshold. 2,039 masks submitted.',
    stack: 'OpenCV · NumPy', link: 'https://github.com/TayalAditya/PSCDL-2026' },
  { y: '2026', name: 'HackerRank Orchestrate', ctx: 'Solo', cats: 'hack',
    desc: 'Rule-based NLP and image checks; 80.8% on 20 labelled samples.',
    stack: 'Python · PIL' },
  { y: '2026', name: 'PodSense', ctx: 'Team of 4 · ABB Accelerator 2026', cats: 'hack',
    desc: 'Design for multi-agent Kubernetes pod observability: four agents and an orchestrator. Idea round.',
    stack: 'LangChain · CrewAI · FastAPI · React · D3' },
  { y: '2026', name: 'MahaDrishti AI', ctx: 'Team of 3 · Pune Agri Hackathon, finalist', cats: 'hack ml',
    desc: 'Verifies farmers’ declared crops per land-record plot from Sentinel-1 and Sentinel-2 imagery, with Marathi and English reports. RF 81.86% in 5-fold CV, mixture-of-experts 83.21%.',
    stack: 'Prithvi-EO 2.0 · FastAPI · Planetary Computer · Gemini' },
  { y: '2026', name: 'UGAC website', ctx: 'Team · mentor', cats: 'institute build',
    desc: 'Hired the council’s web team from 8 candidates in a 2.5-hour live build, mentored the 4 selected and contributed to ugac.iitmandi.ac.in.',
    stack: 'React' },
  { y: '2026', name: 'PRAYAS ML labs', ctx: 'Instructor · PRAYAS 4.0', cats: 'ml',
    desc: 'Four public Colab labs: decision trees, Keras, Q-learning and DQN, computer vision with TFLite quantisation. 2,936 lines, 60 guided experiments.',
    stack: 'Python · Keras · Colab' },
  { y: '2026', name: 'Camouflaged object detection', ctx: 'Paid research', cats: 'ml',
    desc: 'PAIS adapted to camouflaged objects with 10% labels (+7.8 AP), the LGCAD decoder (S-measure 0.847 / 0.865) and a UCOD-DPL reproduction at 0.8407 against the paper’s 0.835.',
    stack: 'PyTorch · mmdetection · DINOv2 · SAM2' },
  { y: '2026', name: 'ISTP: solar panel waste', ctx: 'Team of 5 · IC-301P', cats: 'ml',
    desc: 'Policy research on whether India’s battery-recycling rules transfer to solar-panel waste. Field visit to the Issapur solar plant; recommended viability gap funding and tradable recycling certificates.',
    stack: 'Policy analysis · field study' },
  { y: '2026', name: 'Unlearning CLIP', ctx: 'Team of 4 · CS-683', cats: 'ml',
    desc: 'Beat the published ADU result (72.10 vs 69.96) and adapted SCRUB to whole domains for an 83.6 H-score, 13.6 points over the paper.',
    stack: 'PyTorch · CLIP', link: 'https://github.com/TayalAditya/CS-683' },
  { y: '2026', name: 'Exodia Gate', ctx: 'Solo · Exodia 2026', cats: 'institute build',
    desc: 'QR ticketing, mailing and gate scanning for 200 attendees. Atomic single-use claims blocked 26 reuse attempts; 13 commits shipped live on the day.',
    stack: 'Next.js · tRPC · Prisma · Neon', link: 'https://github.com/TayalAditya/exodia-qr' },
  { y: '2026', name: 'Face EngagementCV', ctx: 'Solo · hiring assignment', cats: 'ml',
    desc: 'Face identification and engagement scoring from classroom CCTV. dlib matching with a MediaPipe fallback down to 20 px, optical flow, clustering of unknown faces.',
    stack: 'dlib · MediaPipe · OpenCV', link: 'https://github.com/TayalAditya/FaceEngagementCV' },
  { y: '2026', name: 'PlanMyDegree', ctx: 'Solo · live', cats: 'institute build',
    desc: 'The degree planner 1,021 IIT Mandi students use: credits, pre-registration with seat caps, timetable clashes, transcript OCR. 30 data models, ~65 API routes, 880+ commits.',
    stack: 'Next.js · Prisma · PostgreSQL · NextAuth', link: 'https://www.planmydegree.app' },
  { y: '2026', name: 'LaTeX lecture notes', ctx: 'Solo · study notes', cats: 'build',
    desc: 'Beamer rewrites of IIT Mandi’s Data Structures, DBMS and Python lectures as clean notes.',
    stack: 'LaTeX' },
  { y: '2026', name: 'No-DL vehicle counter', ctx: 'Solo · Vehant challenge, rank 10', cats: 'ml hack',
    desc: 'A 9-stage classical CV pipeline built in 48 hours with deep learning banned. MAE 16.4 on the hidden test set.',
    stack: 'OpenCV · NumPy' },
  { y: '2025', name: 'SAND 2025', ctx: 'Team of 4 · AIR 1, Global 11', cats: 'ml hack',
    desc: 'Five-class ALS severity from voice recordings, an IEEE ICASSP 2026 challenge. Macro-F1 0.5430 in Task 1; India #2 in Task 2.',
    stack: 'Python · audio ML' },
  { y: '2025', name: 'Amazon ML Challenge', ctx: 'Team of 3', cats: 'ml hack',
    desc: 'Product price prediction across 75,000 items: TF-IDF and regex features into a 21-model LightGBM ensemble. SMAPE 54.38% → 32.33% out-of-fold.',
    stack: 'LightGBM · scikit-learn' },
  { y: '2025', name: 'Neufin', ctx: 'Solo', cats: 'build',
    desc: 'Product catalogue with search, pagination and a cart, Zod validation and Jest tests.',
    stack: 'Next.js 14 · TanStack Query · Zustand', link: 'https://neufin-seven.vercel.app' },
  { y: '2025', name: 'CareerAutofill AI', ctx: 'Solo', cats: 'ml build',
    desc: 'Planner and executor agents with a Chrome extension that fills job forms. LoRA on distilgpt2 (0.18% of weights) took perplexity from 35.7 to 23.2.',
    stack: 'FastAPI · PEFT · spaCy · React', link: 'https://github.com/TayalAditya/CareerAutofillAI' },
  { y: '2025', name: 'SecureInvest-AI', ctx: 'Solo · SEBI hackathon, GFF 2025', cats: 'hack',
    desc: 'A fraud-risk scorer for investment pitches, built in 48 hours.',
    stack: 'MERN · Socket.IO · Redis', link: 'https://github.com/TayalAditya/SecureInvest-AI' },
  { y: '2025', name: 'Adobe India Hackathon', ctx: 'Team leader · Round 2', cats: 'hack ml',
    desc: 'Multilingual PDF outline extraction in an offline, CPU-only Docker image, and persona-aware section ranking across 7 PDFs in 30–45 s.',
    stack: 'PyMuPDF · MiniLM · Docker', link: 'https://tayaladitya.github.io/BasicRedirector/' },
  { y: '2025', name: 'DyslexoFly', ctx: 'Team of 2 · Code for Bharat S2', cats: 'hack build',
    desc: 'Turns PDFs and documents into dyslexia-friendly reading: OpenDyslexic, English and Hindi summaries, audio in 7 neural voices.',
    stack: 'Next.js · Flask · DistilBART · mT5', link: 'https://dyslexofly.vercel.app' },
  { y: '2025', name: 'GCS website', ctx: 'Solo · Guidance & Counselling Services', cats: 'institute build',
    desc: 'Static site for IIT Mandi’s counselling cell: mission, team, self-help and appointments.',
    stack: 'HTML · CSS', link: 'https://tayaladitya.github.io/GCS/' },
  { y: '2025', name: 'Deepfake detection', ctx: 'Team of 6 · CS-671', cats: 'ml',
    desc: 'Frozen CLIP and DINOv2 features with a GPU SVM across 19 image generators and 80,353 test images: 89.4% weighted accuracy.',
    stack: 'CLIP · DINOv2 · cuML' },
  { y: '2025', name: 'CaptureSmart', ctx: 'Team of 6 · 3rd of 60+', cats: 'ml hack',
    desc: 'Android camera assistant. MobileNetV2 blur score (MAE 6.7 on 24,000 images) and ISO and shutter recommendations.',
    stack: 'Kotlin · CameraX · TensorFlow · Flask', link: 'https://github.com/TayalAditya/Group-34_CaptureSmartAI' },
  { y: '2025', name: 'TheBudgetBuddy', ctx: 'Team of 4 · FrostHack 2025', cats: 'hack ml',
    desc: 'Plain-English questions over your own transactions with a LangChain agent, Groq Llama3-70B, Cohere rerank and FAISS.',
    stack: 'LangChain · Groq · FAISS · Streamlit', link: 'https://github.com/TayalAditya/TheBudgetBuddy' },
  { y: '2025', name: 'TheAttendioBot', ctx: 'Solo', cats: 'build',
    desc: 'Telegram bot that tracks attendance and tells you how many classes you can skip. Eight conversation flows, rate-limit auto-blocking.',
    stack: 'python-telegram-bot · Google Sheets · Railway', link: 'https://github.com/TayalAditya/TheAttendioBot' },
  { y: '2025', name: 'Malware scanner', ctx: 'Team of 4 · KrackHack', cats: 'hack build',
    desc: 'Static scanner for .exe, .pdf and .docx files with YARA rules and PE import analysis, behind a React UI.',
    stack: 'FastAPI · YARA · pefile · React', link: 'https://github.com/TayalAditya/MalwareAnalysis_CodeRaftar' },
  { y: '2024', name: 'Faculty Application Portal', ctx: 'IIT Mandi recruitment', cats: 'institute build',
    desc: 'Replaced Google Forms with a Django portal for faculty applications, launched on the official recruitment site, with an admin dashboard and automated CVs and emails.',
    stack: 'Django · SQL', link: 'https://iitmandirec.samarth.edu.in/' },
  { y: '2024', name: 'Autonomous ROS robot', ctx: 'Team of 5', cats: 'build',
    desc: 'ESP32 on a custom 2-layer PCB with a vector-based ROS motion planner.',
    stack: 'ESP32 · ROS · EasyEDA' }
];
